### ISSUE TITLE
`make validate` fails with openscap-1.2.5+

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/scap-security-guide#902]
```
cd Debian/8/ && make
make[1]: Entering directory '/home/slukasik-f22/data/redhat/git/hub/openscap/scap-security-guide/Debian/8'
xsltproc -o output/ssg-debian8-shorthand.xml input/guide.xslt input/guide.xml
xmllint --format --output output/ssg-debian8-shorthand.xml output/ssg-debian8-shorthand.xml
xsltproc -o output/unlinked-unresolved-debian8-xccdf.xml transforms/shorthand2xccdf.xslt output/ssg-debian8-shorthand.xml
oscap xccdf resolve -o output/unlinked-debian8-xccdf.xml output/unlinked-unresolved-debian8-xccdf.xml
xsltproc -o output/unlinked-debian8-xccdf-guide.xml transforms/xccdf-removeaux.xslt output/unlinked-debian8-xccdf.xml
xsltproc -o output/unlinked-notest-debian8-xccdf-guide.xml transforms/xccdf-removetested.xslt output/unlinked-debian8-xccdf.xml
oscap xccdf generate guide --profile allrules output/unlinked-notest-debian8-xccdf-guide.xml > output/ssg-debian8-guide.html
# Make intermediate build/debian8_oval directory to hold final list of OVAL checks for debian8
mkdir -p build/debian8_oval
# Search ../../shared/oval and input/oval directories to find all product specific OVAL checks,
# which are regular files (not symlinks). Merge the final list into build/debian8_oval directory
find ../../shared/oval input/oval -maxdepth 1 -type f -name *.xml -exec cp {} build/debian8_oval ';'
# If openscap on the system supports OVAL-5.11 language version, include also OVAL-5.11 checks
# add local Debian8 specific templated ovals
make -C input/oval/templates all
make[2]: Entering directory '/home/slukasik-f22/data/redhat/git/hub/openscap/scap-security-guide/Debian/8/input/oval/templates'
../../../../../shared/oval/templates/create_package_removed.py packages_removed.csv
../../../../../shared/oval/templates/create_permission_checks.py file_dir_permissions.csv
make[2]: Leaving directory '/home/slukasik-f22/data/redhat/git/hub/openscap/scap-security-guide/Debian/8/input/oval/templates'
make -C input/oval/templates copy
make[2]: Entering directory '/home/slukasik-f22/data/redhat/git/hub/openscap/scap-security-guide/Debian/8/input/oval/templates'
cp output/*.sh ../../remediations/bash/
cp output/*.xml ../../../build/debian8_oval/
make[2]: Leaving directory '/home/slukasik-f22/data/redhat/git/hub/openscap/scap-security-guide/Debian/8/input/oval/templates'
# into final list of OVAL checks
find input/oval/oval_5.11 -maxdepth 1 -type f -name *.xml -exec cp {} build/debian8_oval ';'
find: ‘input/oval/oval_5.11’: No such file or directory
Makefile:30: recipe for target 'checks' failed
make[1]: *** [checks] Error 1
make[1]: Leaving directory '/home/slukasik-f22/data/redhat/git/hub/openscap/scap-security-guide/Debian/8'
Makefile:64: recipe for target 'debian8' failed
make: *** [debian8] Error 2
```

**Comment by isimluk** [comment]
Perhaps we can remove Debian directory from the global `make validate`.

**Comment by msrubar** [comment]
`mkdir Debian/8/input/oval/oval_5.11` can fix this.

**Comment by iankko** [comment]
@msrubar 
> mkdir Debian/8/input/oval/oval_5.11 can fix this. It was also mentioned by ianko in #900.

Correct. That's enough. Do you volunteer to make that PR? (&& Thank you for that! :)).

**Comment by electrosenpai** [comment]
> mkdir Debian/8/input/oval/oval_5.11 can fix this. It was also mentioned by ianko in #900.

This is why I pushed a '.empty' directory in folder oval_5.11, I think git doesn't add empty directory

**Comment by redhatrises** [comment]
PR #905 adds OVAL checks to the `oval_5.11` directory which should fix this issue.

**Comment by iankko** [comment]
Fixed by https://github.com/OpenSCAP/scap-security-guide/issues/903 => closing.

**Comment by iankko** [comment]
And re-open it back. This issue is combining two things together (failing ```make``` with new openscap && failing ```make validate``` for Debian content). The failing ```make``` issue is solved by creating folder for ```oval_5.11```, but the failing ```make validate``` issue is still present there (with both old / pre-OVAL-5.11 and new / supporting OVAL-5.11 content). => Re-opening to have the second subissue fixed too.
